const passwordShow = document.getElementById("password-show");
const generateButton = document.getElementById("btn");

generateButton.addEventListener("click", function passGenerator() {
    const letters = [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        "~",
        "!",
        "@",
        "#",
        "$",
        "%",
        "^",
        "&",
        "*",
        "/",
        "(",
        ")",
        "{",
        "}",
        "[",
        "]",
    ];
    let pass = "";
    function randomNum(e) {
        return Math.floor(Math.random() * e);
    }
    for (i = 0; i <= 8; i++) {
        pass += letters[randomNum(letters.length)];
    }

    passwordShow.textContent = pass;
});
